import Head from 'next/head'
import Image from 'next/image'

import Button from '../comps/buttons/Button'
import NavBar from '../comps/global/Navbar'
import EmojiCard from '../comps/cards/EmojiCard'
import EmojiCardBig from '../comps/cards/EmojiCardBig'
import HighlightCard from '../comps/cards/HighlightCard'
import NutritionCard from '../comps/cards/NutritionCard'
import AmountBar from '../comps/global/AmountBar'
import Bar from '../comps/global/Bar'

import styles from '../styles/Home.module.css'
import styled from 'styled-components'

const Cont = styled.div`
  display: flex;
  flex-direction: column;
  height: 100vh;
  width: 100vw;
  padding: 0 5%;
  justify-content: space-between;
`;

const BtnRow = styled.div`
  display: flex;
  flex-direction: row;
  justify-content: space-between;
  flex-wrap: wrap;
  margin: 20px;
`;

const Headers = styled.p`
  font-size: 24px;
`;

export default function Settings() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar title='Settings' />
      <Cont>
        <Headers>Default Preferences</Headers>
        <BtnRow>
          <Button />
          <Button />
          <Button />
          <Button />
          <Button />
        </BtnRow>

        <Headers>Vitamin</Headers>
        <BtnRow>
          <Button />
          <Button />
          <Button />
          <Button />
          <Button />
        </BtnRow>

        <BtnRow>
          <Button />
          <Button />
          <Button />
          <Button />
          <Button />
        </BtnRow>

        <Headers>Minerals</Headers>
        <BtnRow>
          <Button />
          <Button />
          <Button />
          <Button />
          <Button />
        </BtnRow>

        <BtnRow>
          <Button />
          <Button />
          <Button />
          <Button />
          <Button />
        </BtnRow>

        <Headers>Fat</Headers>
        <BtnRow>
          <Button />
          <Button />
          <Button />
          <Button />
          <Button />
        </BtnRow>

        <BtnRow>
          <Button />
          <Button />
          <Button />
          <Button />
          <Button />
        </BtnRow>
      </Cont>
    </div>
  )
}
